server:
  port: 11000
spring:
  application:
    name: seven-ware
  datasource:
    username: root
    password: 246260
    url: jdbc:mysql://121.4.87.152:3306/seven_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 121.4.87.152:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 121.4.87.152
    virtual-host: /
    listener:
      simple:
        # 手动确认接受消息
        acknowledge-mode: manual
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
logging:
  level:
    io.github.ihelin.seven: debug
myRabbitmq:
  MQConfig:
    queues: stock.release.stock.queue
    delayQueue: stock.delay.queue
    eventExchange: stock-event-exchange
    routingKey: stock.locked
    letterRoutingKey: stock.release
    # 库存自动过期时间 单位:(毫秒)
    ttl: 900000