spring:
  datasource:
    username: root
    password: 246260
    url: jdbc:mysql://121.4.87.152:3306/seven_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 121.4.87.152:8848
  application:
    name: seven-order
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000