server:
  port: 12000
spring:
  application:
    name: seven-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 121.4.87.152:8848
    gateway:
      routes:
        #        - id: test_baidu
        #          uri: https://www.baidu.com
        #          predicates:
        #            - Query=url,baidu
        #        - id: test_qq
        #          uri: https://www.qq.com
        #          predicates:
        #            - Query=url,qq

        - id: seven_product
          uri: lb://seven-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: seven_member
          uri: lb://seven-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: seven_ware
          uri: lb://seven-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: seven_open
          uri: lb://seven-open
          predicates:
            - Path=/api/open/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: seven_admin
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: seven_host_route
          uri: lb://seven-product
          predicates:
            - Host=seven.com

        - id: seven_search_route
          uri: lb://seven-open
          predicates:
            - Host=search.seven.com