server:
  port: 7000
spring:
  application:
    name: seven-coupon
  datasource:
    username: root
    password: 246260
    url: jdbc:mysql://121.4.87.152:3306/seven_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 121.4.87.152:8848
mybatis-plus:
  global-config:
    db-config:
      id-type: auto