server:
  port: 13000
spring:
  application:
    name: seven-open
  cloud:
    nacos:
      discovery:
        server-addr: 121.4.87.152:8848
logging:
  level:
    io.github.ihelin.seven: debug
alibaba:
  cloud:
    access-key: LTAI4G4vjs2kdp8no5mu6pJ2
    secret-key: rAtf9iaChsbnnxEbYnnpIU2hrjzW6X
    oss:
      endpoint: oss-cn-shanghai.aliyuncs.com

